name: defyx_vpn
description: "A new Vpn app."
publish_to: 'none'
version: 3.2.31+191

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Backend Packages
  flutter_riverpod: ^2.5.1
  go_router: ^14.3.1
  shared_preferences: ^2.2.2
  dio: ^5.7.0
  dio_http_formatter: ^3.2.1
  shimmer: ^3.0.0
  shake: ^3.0.0
  vibration: ^3.1.3
  google_mobile_ads: ^6.0.0
  url_launcher: ^6.3.1
  flame: ^1.29.0
  webview_flutter: ^4.13.0
  async: ^2.12.0
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^2.4.4
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.0
  version: ^3.0.2
  flutter_timezone: ^4.1.1
  connectivity_plus: ^7.0.0

  # Frontend Packages
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  lottie: ^3.3.1
  fluttertoast: ^8.2.12
  path_drawing: ^1.0.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  firebase_core: ^4.2.0
  firebase_analytics: ^12.0.3
  battery_plus: ^7.0.0
  no_screenshot: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  retrofit_generator: ^9.1.2
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  riverpod_generator: ^2.4.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/lottie/
    - assets/flags/
    - assets/settings/config.json
    - .env

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900